
package paint2d;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JToggleButton;

/**
 * Class ColorPalette.
 * An interface to work with different colors, allowing selections and action events.
 * @author jlsuarezdiaz
 */
public class ColorPalette extends javax.swing.JPanel {

    /**
     * Creates new form ColorPalette
     */
    public ColorPalette() {
        initComponents();
    }
    
    /**
     * Obtains selected color in the palette.
     * @return Selected color. 
     */
    public Color getSelectedColor(){
        Enumeration<AbstractButton> buttons = btGroupPalette.getElements();
        while(buttons.hasMoreElements()){
            AbstractButton b = buttons.nextElement();
            if(b.isSelected()){
                return b.getBackground();
            }
        }
        return null;
    }
    
    /**
     * Sets to the selected the button in the palette associated to the given color, if it exists.
     * @param c Color to set.
     */
    public void setSelectedColor(Color c){
        Enumeration<AbstractButton> buttons = btGroupPalette.getElements();
        while(buttons.hasMoreElements()){
            AbstractButton b = buttons.nextElement();
            if(b.getBackground().equals(c)){
                b.setSelected(true);
                return;
            }
        }
    }
    
    /**
     * Adds an action listener to all the color buttons in the palette.
     * @param al Action Listener
     */
    public void addActionListener(ActionListener al){
        Enumeration<AbstractButton> buttons = btGroupPalette.getElements();
        while(buttons.hasMoreElements()){
            buttons.nextElement().addActionListener(al);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroupPalette = new javax.swing.ButtonGroup();
        upperPalettePanel = new javax.swing.JPanel();
        blackBt = new javax.swing.JToggleButton();
        redBt = new javax.swing.JToggleButton();
        blueBt = new javax.swing.JToggleButton();
        lowerPalettePanel = new javax.swing.JPanel();
        whiteBt = new javax.swing.JToggleButton();
        yellowBt = new javax.swing.JToggleButton();
        greenBt = new javax.swing.JToggleButton();

        setLayout(new java.awt.BorderLayout());

        blackBt.setBackground(new java.awt.Color(0, 0, 0));
        btGroupPalette.add(blackBt);
        blackBt.setSelected(true);
        blackBt.setMaximumSize(new java.awt.Dimension(24, 24));
        blackBt.setMinimumSize(new java.awt.Dimension(24, 24));
        blackBt.setPreferredSize(new java.awt.Dimension(24, 24));
        upperPalettePanel.add(blackBt);

        redBt.setBackground(new java.awt.Color(255, 0, 0));
        btGroupPalette.add(redBt);
        redBt.setMaximumSize(new java.awt.Dimension(24, 24));
        redBt.setMinimumSize(new java.awt.Dimension(24, 24));
        redBt.setPreferredSize(new java.awt.Dimension(24, 24));
        upperPalettePanel.add(redBt);

        blueBt.setBackground(new java.awt.Color(0, 0, 255));
        btGroupPalette.add(blueBt);
        blueBt.setMaximumSize(new java.awt.Dimension(24, 24));
        blueBt.setMinimumSize(new java.awt.Dimension(24, 24));
        blueBt.setPreferredSize(new java.awt.Dimension(24, 24));
        upperPalettePanel.add(blueBt);

        add(upperPalettePanel, java.awt.BorderLayout.PAGE_START);

        whiteBt.setBackground(new java.awt.Color(255, 255, 255));
        btGroupPalette.add(whiteBt);
        whiteBt.setMaximumSize(new java.awt.Dimension(24, 24));
        whiteBt.setMinimumSize(new java.awt.Dimension(24, 24));
        whiteBt.setPreferredSize(new java.awt.Dimension(24, 24));
        lowerPalettePanel.add(whiteBt);

        yellowBt.setBackground(new java.awt.Color(255, 255, 0));
        btGroupPalette.add(yellowBt);
        yellowBt.setMaximumSize(new java.awt.Dimension(24, 24));
        yellowBt.setMinimumSize(new java.awt.Dimension(24, 24));
        yellowBt.setPreferredSize(new java.awt.Dimension(24, 24));
        lowerPalettePanel.add(yellowBt);

        greenBt.setBackground(new java.awt.Color(0, 255, 0));
        btGroupPalette.add(greenBt);
        greenBt.setMaximumSize(new java.awt.Dimension(24, 24));
        greenBt.setMinimumSize(new java.awt.Dimension(24, 24));
        greenBt.setPreferredSize(new java.awt.Dimension(24, 24));
        lowerPalettePanel.add(greenBt);

        add(lowerPalettePanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton blackBt;
    private javax.swing.JToggleButton blueBt;
    private javax.swing.ButtonGroup btGroupPalette;
    private javax.swing.JToggleButton greenBt;
    private javax.swing.JPanel lowerPalettePanel;
    private javax.swing.JToggleButton redBt;
    private javax.swing.JPanel upperPalettePanel;
    private javax.swing.JToggleButton whiteBt;
    private javax.swing.JToggleButton yellowBt;
    // End of variables declaration//GEN-END:variables
}
